### ISSUE TITLE
As a user, I want to see various drop-off sites so that I can drop my recyclables at any one of those locations

### ISSUE THREAD

**Issue by bojianwangny** [gcivil-nyu-org/S2022-Team-3-repo#10]
**User story**
As a user, I want to see various drop-off sites so that I can drop my recyclables at any one of those locations.

Apart from this, it should also pass the unit tests and must be integrated into the actual site on Heroku.
**Acceptance criteria**
1. Page where the users can scroll through a list of drop-off locations that are filtered based on the user's preferences like location (#4) & item category (#39).
2. Each drop-off site should have a card view that includes (#35).
3. Each card must be arranged in a vertical order to form a list.
4. If there is no site to list particular filter criteria I should see a text message that says: "Sorry, we are unable to find drop-off sites that match your preferences. Please try something else."

**Definition of Done**
I know this is done when I can see a list of drop-off sites and if nothing matches the user's preferences then I can see the message "Sorry, we are unable to find drop-off sites that match your preferences. Please try something else."

**Comment by KevinPatel04** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S2022-workspace-620189b09c1e3d001abf18bf/issues/gcivil-nyu-org/S2022-Team-3-repo/10?planning-poker) with ZenHub @bojianwangny @meisun0107 @pb2640

**Comment by KevinPatel04** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S2022-workspace-620189b09c1e3d001abf18bf/issues/gcivil-nyu-org/S2022-Team-3-repo/10?planning-poker) with ZenHub @TheHarbinger99
