### ISSUE TITLE
As a user, I want to see the nearby drop-off locations so that I can pick the nearest drop-off location from my specified location.

### ISSUE THREAD

**Issue by bojianwangny** [gcivil-nyu-org/S2022-Team-3-repo#11]
**User story**
As a user, I want to see the nearby drop-off locations so that I can pick the nearest drop-off location from my specified location. 

Apart from this, it should also pass the unit tests and must be integrated into the actual site on Heroku.

**Acceptance criteria**
1. I want to see the drop-off sites sorted in increasing order based on the distance from the location that the user chose to that drop-off site.
2. Need to calculate the distance for the filtered drop-off sites from my preferred location
3. The list of the drop of the site (#10) should be sorted based on how far are they from my preferred location in increasing order.

**Definition of Done**
I know this user story is done when I get the list of drop-off sites sorted in increasing order of distance from my preferred location.

**Comment by KevinPatel04** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S2022-workspace-620189b09c1e3d001abf18bf/issues/gcivil-nyu-org/S2022-Team-3-repo/11?planning-poker) with ZenHub @bojianwangny @meisun0107 @pb2640

**Comment by KevinPatel04** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S2022-workspace-620189b09c1e3d001abf18bf/issues/gcivil-nyu-org/S2022-Team-3-repo/11?planning-poker) with ZenHub @TheHarbinger99
