### ISSUE TITLE
As a user, I want my posts to be shown on the website so that other users can see them and contact me.

### ISSUE THREAD

**Issue by bojianwangny** [gcivil-nyu-org/S2022-Team-3-repo#12]
**User story**
As a user, I want my posts to be shown on the website so that other users can see them and contact me.

**Acceptance criteria**
1. The ad that the user posts should be displayed on the search donation item page.

**Definition of Done**
I can say it is done when I see the post which I created in the list on the search page.

**Comment by KevinPatel04** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S2022-workspace-620189b09c1e3d001abf18bf/issues/gcivil-nyu-org/S2022-Team-3-repo/12?planning-poker) with ZenHub @bojianwangny @meisun0107 @pb2640

**Comment by KevinPatel04** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S2022-workspace-620189b09c1e3d001abf18bf/issues/gcivil-nyu-org/S2022-Team-3-repo/12?planning-poker) with ZenHub @TheHarbinger99
