### ISSUE TITLE
As a user, I want to be able to search the nearby NGOs for dropping off items by using my current location’s information so that I can pick a suitable location to donate my stuff.

### ISSUE THREAD

**Issue by bojianwangny** [gcivil-nyu-org/S2022-Team-3-repo#13]
**User story**
As a user, I want to be able to search the nearby NGOs for dropping off items by using my current location’s information so that I can pick a suitable location to donate my stuff.

**Acceptance criteria**

**Definition of Done**

**Comment by KevinPatel04** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S2022-workspace-620189b09c1e3d001abf18bf/issues/gcivil-nyu-org/S2022-Team-3-repo/13?planning-poker) with ZenHub @bojianwangny @meisun0107 @pb2640

**Comment by KevinPatel04** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S2022-workspace-620189b09c1e3d001abf18bf/issues/gcivil-nyu-org/S2022-Team-3-repo/13?planning-poker) with ZenHub @TheHarbinger99
