### ISSUE TITLE
As a user, I want to see a list view of items available for donations so that I can see what items other people are willing to donate.

### ISSUE THREAD

**Issue by bojianwangny** [gcivil-nyu-org/S2022-Team-3-repo#15]
**User story**
As a user, I want to see a list view of items available for donations so that I can see what items other people are willing to donate.

**Acceptance criteria**
1.  When I go on this page I see a page where all the item ads are displayed.
2. Each ad should be shown in a form of a card.  

**Definition of Done**
When I go on this page I see a list of cards for item ads posted by users in past.

**Comment by KevinPatel04** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S2022-workspace-620189b09c1e3d001abf18bf/issues/gcivil-nyu-org/S2022-Team-3-repo/15?planning-poker) with ZenHub @bojianwangny @meisun0107 @pb2640

**Comment by KevinPatel04** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S2022-workspace-620189b09c1e3d001abf18bf/issues/gcivil-nyu-org/S2022-Team-3-repo/15?planning-poker) with ZenHub @TheHarbinger99
