### ISSUE TITLE
As a user, I want to be able to look for actual drop off locations across NYC so that I can pick the drop-off location for dropping off my item.

### ISSUE THREAD

**Issue by bojianwangny** [gcivil-nyu-org/S2022-Team-3-repo#16]
**User story**
As a user, I want to be able to look for actual drop-off locations across NYC so that I can pick the drop-off location for dropping off my item.

**Acceptance criteria**
1. I am able to see various drop-off sites across NYC available on NYC open data. 
2. The records are updated on 

**Definition of Done**

**Comment by KevinPatel04** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S2022-workspace-620189b09c1e3d001abf18bf/issues/gcivil-nyu-org/S2022-Team-3-repo/16?planning-poker) with ZenHub @bojianwangny @meisun0107 @pb2640

**Comment by KevinPatel04** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S2022-workspace-620189b09c1e3d001abf18bf/issues/gcivil-nyu-org/S2022-Team-3-repo/16?planning-poker) with ZenHub @TheHarbinger99
