### ISSUE TITLE
Testing party bug: XSS attack in green wall page

### ISSUE THREAD

**Issue by furrkai** [gcivil-nyu-org/S2022-Team-3-repo#207]
<img width="812" alt="1650151823(1)" src="https://user-images.githubusercontent.com/83237232/163694239-e837596f-9bc8-4474-95cf-236ed58b01f2.png">

<img width="1075" alt="1650152038(1)" src="https://user-images.githubusercontent.com/83237232/163694327-f5339ffc-31f8-49b9-b624-9ecce409ef00.png">

For the upload form to green wall, the caption field can inject an XSS payload to execute malicious codes on this page
https://greencan.herokuapp.com/rewards/gallery/

**Comment by KevinPatel04** [comment]
Resolved!
