### ISSUE TITLE
Testing Party

### ISSUE THREAD

**Issue by bc3177** [gcivil-nyu-org/S2022-Team-3-repo#208]
1. When a very long input is given in the search bar, the page is crashing.

<img width="1440" alt="Screen Shot 2022-04-17 at 1 39 06 PM" src="https://user-images.githubusercontent.com/90463880/163726224-04fca8f6-bd24-4f5d-9422-dc66f453eb62.png">

**Comment by KevinPatel04** [comment]
Can you tell me how long was your input? Bcz I tried with 4000 characters but I am not able to reproduce this.

**Comment by bc3177** [comment]
I used a string of 10,000 characters.
