### ISSUE TITLE
A minor Bug

### ISSUE THREAD

**Issue by Pruthviraj98** [gcivil-nyu-org/S2022-Team-3-repo#209]
There is a minor bug where phone number is validated. Even though a valid "number" is entered, it asks to enter a valid number. (It is a minor bug). 

![Screen Shot 2022-04-17 at 1.33.30 PM.png](https://images.zenhubusercontent.com/6204657c5153f31dc249bc95/672cabfb-152e-44df-8446-56ed9dbf1e5f)

**Comment by KevinPatel04** [comment]
How is this a valid number? 

And can you tell us how you got the message twice?

**Comment by Pruthviraj98** [comment]
As per my belief, this is a valid number but not a valid phone number. As there were two errors, I got confused.

**Comment by KevinPatel04** [comment]
Oh ok. We thought you are complaining about the validation that the number that you enter is a valid phone number.

**Comment by KevinPatel04** [comment]
Resolved!
