### ISSUE TITLE
Testing Party Bug (Database Security Issue)

### ISSUE THREAD

**Issue by manektamanna** [gcivil-nyu-org/S2022-Team-3-repo#212]
The GitHub repo has the env file listed which provides credentials to log in to the application database, compromising the entire application database. This is a major security issue.

![Screenshot (397)](https://user-images.githubusercontent.com/85683392/163729822-39d80f53-b6c7-49d0-b476-3f5e79743c70.png)

**Comment by KevinPatel04** [comment]
Resolved!
