### ISSUE TITLE
Testing Party

### ISSUE THREAD

**Issue by aaronk4311** [gcivil-nyu-org/S2022-Team-3-repo#214]
1. When trying to sign up for a new account, I get the following error: 
```An error occurred. Please ensure you have good internet connection and you have entered a valid email address```. I would see if it would be possible to make the error message more specific and perhaps highlight the specific textbox that is causing the error (and also keep what the user entered to avoid re-entering them on error).
The following were credentials I tried to sign up with:
First Name: test
Last Name: account
Email: asd123@gmail.com
Password: testPassword1

2. If I open the sign-up form, log in to an existing account from a separate window, and then try to sign up, it gives an error page with the following message: 
```
Forbidden (403)

CSRF verification failed. Request aborted.
```

**Comment by KevinPatel04** [comment]
1. Is `asd123@gmail.com` a valid email address? The message says `...and you have entered a valid email address`. You can only create an account after successful email validation.

2.  Can you please share the credentials which you used to log in so that we can reproduce the error?

**Comment by aaronk4311** [comment]
1. Yes, asd123@gmail.com is a valid email address. I tried to create a new gmail account and it said asd123 already exists. It still gave that error upon trying to create a greenCan account.
2. I had two separate windows open - one for login and one for signup. I logged in first, then went to the signup window to create an account. I don't think it matters what was entered to sign up in this case, but these were the credentials I used to sign up:
First Name: first
Last Name: last
Email: asd123@gmail.com
Passord: 1234

**Comment by KevinPatel04** [comment]
1. Google STMP blocks third-party apps to send emails once you reach a certain threshold limit per day per domain.

We didn't change anything and it is working today. Yesterday many people tested the app thus sending emails through Gmail was throwing errors as we reached that threshold thus, you were seeing that alert message and not able to signup.

**Comment by KevinPatel04** [comment]
Resolved!
