### ISSUE TITLE
Testing Bugs

### ISSUE THREAD

**Issue by chinmaykulkarni95** [gcivil-nyu-org/S2022-Team-3-repo#215]
Found this below bugs:

1. Previous images in image upload are getting flushed. Open a page where multiple image upload functionality is implemented, like create post, add few images in the upload image section. Again click on image upload, the file explorer will open, without selecting anything click on cancel. The previous uploaded images are getting flushed.

2. While creating post I can give email address like $^_@a, this string does not represent the email pattern ([a-z]@[a-z].[a-z])

3. The images on the reuse -> want to donate page at the bottom, are actually links to google map. The cursor does not change to pointer when you hover on them. 

4. Could enter an invalid zip code 
![Screen Shot 2022-04-17 at 7.09.36 PM.png](https://images.zenhubusercontent.com/62069902d96923fd99045c25/2fb05137-6af6-45ef-968b-6c98ef7dde67)

**Comment by KevinPatel04** [comment]
4. Can you please tell me how did you manage to do this so that we can reproduce the error? Bcz currently, I am not able to type any further than 5 digits.

**Comment by KevinPatel04** [comment]
Resolved!
