### ISSUE TITLE
Testing Party  #2

### ISSUE THREAD

**Issue by srijanmalhotra2711** [gcivil-nyu-org/S2022-Team-3-repo#217]
1. I tried to **create a new account** using both my Yahoo and Gmail id but received this error constantly. 

![Screen Shot 2022-04-17 at 20.53.05.png](https://images.zenhubusercontent.com/62052e0dcd174000595a4a54/5637136a-8370-4737-9e35-4a9df24c47f8)

![Screen Shot 2022-04-17 at 20.53.31.png](https://images.zenhubusercontent.com/62052e0dcd174000595a4a54/050b0dc1-ec5e-43cf-b979-7e5d86b831c0)

2. I was able to add an **invalid zip code**, which is greater than the length of 5. 

![Screen Shot 2022-04-17 at 20.50.51.png](https://images.zenhubusercontent.com/62052e0dcd174000595a4a54/d9f42f51-586e-418e-b52c-78ff3799a73c)

**Comment by KevinPatel04** [comment]
1. Google STMP blocks third-party apps to send emails once you reach a certain threshold limit per day per domain.

We didn't change anything and it is working today. Yesterday many people tested the app thus sending emails through Gmail was throwing errors as we reached that threshold thus, you were seeing that alert message and not able to signup.
