### ISSUE TITLE
As a user, I want to type the zip code in a search bar so that I can search nearby drop-off locations

### ISSUE THREAD

**Issue by bojianwangny** [gcivil-nyu-org/S2022-Team-3-repo#4]
**User story**
As a user, I want to type the zip code in a search bar so that I can search nearby drop-off locations.

**Acceptance criteria**
1. Need an input text box where users can enter their zip code to search.
2. Zip code should be numeric 5 digits only and must be a valid NYC Zip code. If the Zip code is not a valid NYC zip code then I should get a warning "Please enter a valid NYC zip code".
3. Once the user clicks on the search button the results of the drop-off locations should be filtered and should display the drop-off locations for that particular zip code.

**Definition of Done**
I know this would be done when I go to this page I see a search bar where I can enter a zip code along with a button when clicked to filter out the drop-off locations for that particular neighborhood. The filtered records should be displayed on the map using markers and in form of a list.

Apart from this, it should also pass the unit tests and must be integrated into the actual site on Heroku.

**Comment by KevinPatel04** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S2022-workspace-620189b09c1e3d001abf18bf/issues/gcivil-nyu-org/S2022-Team-3-repo/4?planning-poker) with ZenHub @pb2640 @bojianwangny @meisun0107

**Comment by KevinPatel04** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S2022-workspace-620189b09c1e3d001abf18bf/issues/gcivil-nyu-org/S2022-Team-3-repo/4?planning-poker) with ZenHub @TheHarbinger99
